name: menu_inline_filter
description: animated menu filter
version: 0.0.2
homepage: https://kevinmendez.fi/
repository: https://github.com/kevinrmendez/menu_inline_filter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
